# 
# CircleCI 2.0 Gatsby Github Pages Configuration File
#

version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10

    working_directory: ~/gatsby-site

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      
      - run:
          name: Install Dependencies
          command: yarn

      - save_cache: 
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ./node_modules     

      - run:
          name: Gatsby Build
          command: |
            ./node_modules/.bin/gatsby build --prefix-paths
            git config user.email "ci-bot@lazers.tv"
            git config user.name "lazersbot"

      - add_ssh_keys:
          fingerprints:
            - "13:c6:22:7f:3b:87:56:00:75:56:e2:2c:dc:cc:e7:be"
      
      - run:
          name: Github Pages Deploy
          command: ./node_modules/.bin/gh-pages -d public