# 
# CircleCI 2.0 Gatsby Github Pages Configuration File
#

version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10

    working_directory: ~/gatsby-site

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      
      - run:
          name: Install Dependencies
          command: yarn

      - save_cache: 
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - ./node_modules     

      - run:
          name: Gatsby Build
          command: |
            ./node_modules/.bin/gatsby build --prefix-paths
            git config user.email "contact+bot@lazers.tv"
            git config user.name "lazersbot"

      - add_ssh_keys:
          fingerprints:
            - "1d:22:bb:a5:12:71:1c:e1:a9:3f:0e:ec:8b:ca:d0:32"
      
      - run:
          name: Github Pages Deploy
          command: ./node_modules/.bin/gh-pages -d public